package pl.easybud.ui.views.admin.user;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import pl.easybud.backend.data.entity.User;
import pl.easybud.ui.views.admin.RoleSelect;
import com.vaadin.ui.Button;
import com.vaadin.ui.Grid;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class UserAdminViewDesign extends VerticalLayout {
	protected TextField search;
	protected Button add;
	protected Grid<User> list;
	protected VerticalLayout form;
	protected TextField email;
	protected TextField name;
	protected TextField password;
	protected RoleSelect role;
	protected Button update;
	protected Button cancel;
	protected Button delete;

	public UserAdminViewDesign() {
		Design.read(this);
	}
}
