package pl.easybud.ui.views;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class AccessDeniedDesign extends VerticalLayout {
  public AccessDeniedDesign() {
    Design.read(this);
  }
}
