package pl.easybud.ui.views.admin.job;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.DateField;
import com.vaadin.ui.Grid;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;
import pl.easybud.backend.data.entity.Job;
import pl.easybud.ui.views.admin.JobStatusSelect;

@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class JobAdminViewDesign extends VerticalLayout {
  protected TextField search;
  protected Button add;
  protected CssLayout listParent;
  protected Grid<Job> list;
  protected VerticalLayout form;
  protected TextField name;
  protected TextField label;
  protected JobStatusSelect status;
  protected TextField address;
  protected DateField start;
  protected DateField end;
  protected TextArea description;
  protected Button update;
  protected Button cancel;
  protected Button delete;

  public JobAdminViewDesign() {
    Design.read(this);
  }
}
