package pl.easybud.ui.views.admin.contractor;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.Grid;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;
import pl.easybud.backend.data.entity.Contractor;
import pl.easybud.backend.data.entity.Employee;
import pl.easybud.ui.views.admin.EmployeeStatusSelect;

@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class ContractorAdminViewDesign extends VerticalLayout {
  protected TextField search;
  protected Button add;
  protected CssLayout listParent;
  protected Grid<Contractor> list;
  protected VerticalLayout form;
  protected TextField name;
  protected TextField label;
  protected TextField nip;
  protected TextField regon;
  protected TextArea description;
  protected Button update;
  protected Button cancel;
  protected Button delete;

  public ContractorAdminViewDesign() {
    Design.read(this);
  }
}
