package pl.easybud.ui.views.admin.equipment;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.DateField;
import com.vaadin.ui.Grid;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;
import pl.easybud.backend.data.entity.Equipment;
import pl.easybud.ui.views.admin.ToolStatusSelect;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class EquipmentAdminViewDesign extends VerticalLayout {
  protected TextField search;
  protected Button add;
  protected CssLayout listParent;
  protected Grid<Equipment> list;
  protected VerticalLayout form;
  protected TextField name;
  protected TextField label;
  protected ToolStatusSelect status;
  protected DateField purchase;
  protected TextField serialNumber;
  protected DateField quarantee;
  protected Button update;
  protected Button cancel;
  protected Button delete;

  public EquipmentAdminViewDesign() {
    Design.read(this);
  }
}
