package pl.easybud.ui;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class MainViewDesign extends HorizontalLayout {
  protected Label activeViewName;
  protected Button menuButton;
  protected CssLayout menu;
  protected Button jobs;
  protected Button users;
  protected Button employees;
  protected Button vehicles;
  protected Button equipments;
  protected Button contractors;
  protected Button logout;
  protected VerticalLayout content;

  public MainViewDesign() {
    Design.read(this);
  }
}
